[tool.poetry]
name = "mech"
version = "0.1.0"
description = ""
authors = ["8baller <8ball030@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
open-autonomy = "==0.10.5.post1"
autonomy-dev = "^0.1.1"
mypy = "^1.3.0"
pylint = "^2.17.4"
openai = "0.27.2"
requests = "2.28.2"
mech-client = "^0.1.1"


[tool.poetry.group.dev.dependencies]
black = "22.6.0"
isort = "5.10.1"
pylama = "^8.4.1"
py-eth-sig-utils = "0.4.0"
hypothesis = "6.75.3"
grpcio = "1.54.2"
asn1crypto = "1.5.1"
open-aea-ledger-ethereum = "1.34.0"
open-aea-ledger-cosmos = "1.34.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

