[tool.poetry]
name = "mech"
version = "0.1.0"
description = ""
authors = [
    "8baller <8ball030@gmail.com>",
    "David Vilela <dvilelaf@gmail.com>",
    "David Minarsch <david.minarsch@googlemail.com>",
    "Justice Mace <justice.mace@valory.xyz>",
    "Ardian Abazi <ardian.abazi@valory.xyz>",
    "Jose Moreira Sanchez <jose.moreira.sanchez@valory.xyz>",
    "Adamantios Zaras <adamantios.zaras@valory.xyz>",
]
readme = "README.md"
repository = "https://github.com/valory-xyz/mech"
keywords = ["mech", "autonomy", "autonomous", "autonolas", "service", "multi", "agent"]
classifiers = [
    "Environment :: Console",
    "Environment :: Web Environment",
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Natural Language :: English",
    "Operating System :: MacOS",
    "Operating System :: Microsoft",
    "Operating System :: Unix",
    "Programming Language :: Python :: 3.10",
    "Topic :: Communications",
    "Topic :: Internet",
    "Topic :: Scientific/Engineering",
    "Topic :: Software Development",
    "Topic :: System",
]
packages = [{include = "packages"}]

[tool.poetry.dependencies]
python = "^3.10"
open-autonomy = "==0.10.5.post1"
autonomy-dev = "^0.1.1"
mypy = "^1.3.0"
pylint = "^2.17.4"
openai = "0.27.2"
requests = "2.28.2"
mech-client = "^0.1.5"

[tool.poetry.group.dev.dependencies]
tomte = {version = "==0.2.12", extras = ["cli", "tests"]}
pylama = "^8.4.1"
py-eth-sig-utils = "0.4.0"
hypothesis = "6.75.3"
grpcio = "1.54.2"
asn1crypto = "1.5.1"
open-aea-ledger-ethereum = "1.34.0"
open-aea-ledger-cosmos = "1.34.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
