agent_name: mech
author: valory
version: 0.1.0
license: Apache-2.0
description: ''
aea_version: '>=1.33.0, <2.0.0'
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- eightballer/websocket_client:0.1.0:bafybeicqkljjzvdl4v7pzbmsfd3al7uv7563x3qa5gmnzxeuoxgtmolpta
- valory/abci:0.1.0:bafybeiengwzb2xyi2uognosc4ywdf4o3eqiktmeinn5y6pehqiqt55muf4
- valory/http_client:0.23.0:bafybeicxuedaogf2q4z3zekgr2yvsxt6tieo3fzv7deg3734datprtsyry
- valory/ipfs:0.1.0:bafybeic4uifneblfrd4wq7nljkhbd6jajqoczlpyfil5dq6pb6jpkatgcq
- valory/ledger:0.19.0:bafybeiehwka634iicodmzolflo2le6pdlfmb4dgtnhszjcccoanyay75gm
- valory/p2p_libp2p_client:0.1.0:bafybeidfm65eece533hfvg2xyn4icpmvz4lmvbemstrlo3iuffb7e72ycq
contracts:
- valory/agent_mech:0.1.0:bafybeifjjnnbtqttvq3ox5fpmdbppl5vzkcbfdnxes3bdt4z53ayet2yiy
- valory/gnosis_safe:0.1.0:bafybeiapw4acnlm4emf5d53jwh5aoytkmwnd6awd3ustb5622jenjkev34
- valory/gnosis_safe_proxy_factory:0.1.0:bafybeia3bzij3sdy7binqkuwnqwpqzkko3lnysekffiqrpjcnefxxoj6le
- valory/multisend:0.1.0:bafybeicj5ob6zekorswg6j6uf7rg2ft56so4kulkevpcuzxyhww6gnh4xq
- valory/service_registry:0.1.0:bafybeiamcicmf2rjnq3zd6hrirj3vevnwogsyvjt76yi4blwwtwk7yqliu
protocols:
- fetchai/default:1.0.0:bafybeig3w57l7laofhuyl7nco2lfzgtbqf4cto75edfccymugtixjqnm6y
- open_aea/signing:1.0.0:bafybeigqmouus33blg3ttpbtmy2tbhzyaefeyumxhfzxobpw43mocf7sru
- valory/abci:0.1.0:bafybeifsttranjnxstpoyswpm2dzfyzimpatdfbu5pdpu7ibmda5x24ipe
- valory/acn:1.1.0:bafybeif2th25e4gaejgpg373wal4bkpyfxdbee7f7gbrb64vrgrwhbakxm
- valory/contract_api:1.0.0:bafybeihzhpxgwxkapv73bc5mytc77u557e7upmmahgoyqndysjkzvxxcyy
- valory/http:1.0.0:bafybeieshrrplt5oadws5tz3rhjo6m2spchdyhkwa2z6ze2bs4ivauusfq
- valory/ipfs:0.1.0:bafybeidjn5fa2tjah3jif4tt67rccvtflkmkj5gnjq2jssdkxdzwrzzasy
- valory/ledger_api:1.0.0:bafybeiachflkr2syxjzele5ie7tioozyfqpb3u4r2h7vs66jiqrzhineyy
- valory/tendermint:0.1.0:bafybeib25ulpp3tri3ppexk4t6yttuajhr7wpgs7wajpsnbbnzo256ubem
skills:
- eightballer/contract_subscription:0.1.0:bafybeifqgxfdljed46swbd7352vhkiveinifscyjje5hztxbv3wbjz32iu
- valory/abstract_abci:0.1.0:bafybeieme4bswcztypobk4ivxv2ayyttjlldfybrtgusvccev5vmaebitu
- valory/abstract_round_abci:0.1.0:bafybeidokmoxnlaw3kflf2wwrmvae7tuldklp3xehqzhdijgywf75op4my
- valory/mech_abci:0.1.0:bafybeifwrx7lwfzgswma3qiqywjjgqg7buuglrlvo4opkv2txoqewwxe6y
- valory/multiplexer_abci:0.1.0:bafybeigdqv4x5ipvv5czef3tdzrxv3i6wdff74osily2feqwkrafp3ewuu
- valory/registration_abci:0.1.0:bafybeifjubdxnij5mijfgp5hchcy42xq3zs3xd3aqi4ckfkga23c6255vi
- valory/reset_pause_abci:0.1.0:bafybeibewhznknbxy3llqdum7fv65j6fcqvubxklhuz4dxjmi4lbohu6bq
- valory/task_execution_abci:0.1.0:bafybeid7qeftqies5zzwjtro5zhf355bwd2mdbtgcug4e4wbshzkcc7hj4
- valory/termination_abci:0.1.0:bafybeiachuwj7wmnkxjod4ajbf5ico2rhbelraz5h27tesekvk2pan4eqq
- valory/transaction_preparation_abci:0.1.0:bafybeibgb6khaokc33s5io3k2txvolqjkh7v3t7lui2srsph37m5i7fk34
- valory/transaction_settlement_abci:0.1.0:bafybeiaipca2dcqipr4bq7f2uz3te7drmvvy3l6rv5gdkjcs6ntke7tnhu
default_ledger: ethereum
required_ledgers:
- ethereum
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  version: 1
  disable_existing_loggers: false
  formatters:
    standard:
      format: '[%(asctime)s] [%(levelname)s] %(message)s'
  handlers:
    logfile:
      class: logging.FileHandler
      formatter: standard
      filename: ${LOG_FILE:str:log.txt}
      level: ${LOG_LEVEL:str:INFO}
    console:
      class: logging.StreamHandler
      formatter: standard
      stream: ext://sys.stdout
  loggers:
    aea:
      handlers:
      - logfile
      - console
      propagate: true
dependencies:
  open-aea-ledger-ethereum: {}
default_connection: null
---
public_id: eightballer/websocket_client:0.1.0:bafybeiexove4oqyhoae5xmk2hilskthosov5imdp65olpgj3cfrepbouyy
type: connection
config:
  endpoint: ${str:wss://rpc.gnosischain.com/wss}
  target_skill_id: eightballer/contract_subscription:0.1.0
---
public_id: eightballer/contract_subscription:0.1.0:bafybeiby5ajjc7a3m2uq73d2pprx6enqt4ghfcq2gkmrtsr75e4d4napi4
type: skill
behaviours:
  subscriptions:
    args:
      contracts:
      - '0xFf82123dFB52ab75C417195c5fDB87630145ae81'
---
public_id: valory/abci:0.1.0
type: connection
config:
  target_skill_id: valory/mech_abci:0.1.0
  host: ${str:localhost}
  port: ${int:26658}
  use_tendermint: ${bool:false}
---
public_id: valory/p2p_libp2p_client:0.1.0
type: connection
config:
  nodes:
  - uri: ${str:acn.staging.autonolas.tech:9005}
    public_key: ${str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
cert_requests:
- identifier: acn
  ledger_id: ethereum
  message_format: '{public_key}'
  not_after: '2024-01-01'
  not_before: '2023-01-01'
  public_key: ${str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
  save_path: .certs/acn_cosmos_9005.txt
is_abstract: false
---
public_id: valory/mech_abci:0.1.0
type: skill
models:
  params:
    args:
      sleep_time: 1
      tendermint_check_sleep_delay: 3
      tendermint_p2p_url: ${str:localhost:26656}
      tendermint_com_url: ${str:http://localhost:8080}
      tendermint_max_retries: 5
      tendermint_url: ${str:http://localhost:26657}
      use_termination: ${bool:false}
      agent_mech_contract_address: ${str:0xFf82123dFB52ab75C417195c5fDB87630145ae81}
      reset_period_count: ${int:1000}
      setup:
        all_participants: ${list:["0x10E867Ac2Fb0Aa156ca81eF440a5cdf373bE1AaC"]}
        safe_contract_address: ${str:0x5e1D1eb61E1164D5a50b28C575dA73A29595dFf7}
      file_hash_to_tools_json: '{"bafybeifu2ytuac4nhaf5hsgr6g5ksjtfckwb47nzeqrcih6q3gk5lomdp4":
        ["openai-text-davinci-002", "openai-text-davinci-003", "openai-gpt-3.5-turbo",
        "openai-gpt-4"]}'
      api_keys_json: '{"openai": "dummy_api_key"}'
---
public_id: valory/ledger:0.19.0
type: connection
config:
  ledger_apis:
    ethereum:
      address: ${str:https://rpc.gnosischain.com/}
      chain_id: 100
      poa_chain: false
      default_gas_price_strategy: eip1559
