agent_name: mech
author: eightballer
version: 0.1.0
license: Apache-2.0
description: ''
aea_version: '>=1.33.0, <2.0.0'
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- eightballer/websocket_client:0.1.0:bafybeihwcracii3fvvdbvku2wmz7ephsi6dlhycisq5yn3xemryxovqn5i
contracts: []
protocols:
- fetchai/default:1.0.0:bafybeig3w57l7laofhuyl7nco2lfzgtbqf4cto75edfccymugtixjqnm6y
- open_aea/signing:1.0.0:bafybeibqlfmikg5hk4phzak6gqzhpkt6akckx7xppbp53mvwt6r73h7tk4
skills:
- eightballer/contract_subscription:0.1.0:bafybeif7epfsq5rmmtam2oqyhspem2jfcwdtyd4i6k5mgxiea3wyjm5s74
default_ledger: ethereum
required_ledgers:
- ethereum
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  disable_existing_loggers: false
  version: 1
dependencies:
  open-aea-ledger-ethereum: {}
default_connection: null
---
public_id: eightballer/websocket_client:0.1.0:bafybeiexove4oqyhoae5xmk2hilskthosov5imdp65olpgj3cfrepbouyy
type: connection
config:
  endpoint: wss://polygon-mainnet.g.alchemy.com/v2/NoF8MPitnddMlyaaSSIg2ix4tt66N11U
  target_skill_id: eightballer/contract_subscription:0.1.0
---
public_id: eightballer/contract_subscription:0.1.0:bafybeiby5ajjc7a3m2uq73d2pprx6enqt4ghfcq2gkmrtsr75e4d4napi4
type: skill
behaviours:
  subscriptions:
    args:
      contracts:
      - '0xf25212e676d1f7f89cd72ffee66158f541246445'
